name: '.NET NuGet add source'
description: '.NET NuGet add source GitHub action'
inputs:
  username:
    description: 'GitHub username'
    required: true
  password:
    description: 'A personal access token with access to the GitHub repository.'
    required: true
  name:
    description: 'NuGet Package Source Name'
    required: true
  source:
    description: 'NuGet Package URL'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"