name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '17'

      - run: npm install

      - name: ncc build
        run: |
          npx @vercel/ncc build src/main.ts

  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - run: npm install

      - uses: ./
        with:
          username: ${{ secrets.GIT_CREDENTIAL_USERNAME }}
          password: ${{ secrets.GIT_CREDENTIAL_PACKAGE_PASSWORD }}
          name: "GitHub Packages"
          source: ${{ secrets.GIT_CREDENTIAL_PACKAGE_SOURCE }}
