name: Build

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm run build

  Test:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [ ubuntu-latest, macos-latest, windows-latest ]
        VERSION: [ 6.x, 7.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.VERSION }}

      - uses: ./
        with:
          username: ${{ secrets.GIT_CREDENTIAL_USERNAME }}
          password: ${{ secrets.GIT_CREDENTIAL_PACKAGE_PASSWORD }}
          name: "GitHub Packages"
          source: ${{ secrets.GIT_CREDENTIAL_PACKAGE_SOURCE }}
