name: Test

on: push

jobs:
  Test:
    runs-on: ${{ matrix.OS }}
    strategy:
      matrix:
        OS: [ ubuntu-latest, macos-latest, windows-latest ]
        VERSION: [ 6.x, 7.x, 8.x, 9.x ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.VERSION }}

      - uses: ./
        with:
          username: akiojin
          password: Test012345
          name: "GitHub Packages"
          source: https://nuget.pkg.github.com/akiojin/index.json
